# Generated by Django 5.0.6 on 2024-11-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_lesson_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/thumbnails/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/'),
        ),
    ]
