# Generated by Django 5.0.6 on 2024-11-08 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
    ]
