# Generated by Django 5.0.6 on 2024-11-08 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_remove_lesson_content_remove_lesson_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='courseenrollment',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, to='firstapp.lesson'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.course'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='enrolled_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
