# Generated by Django 5.0.6 on 2024-11-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_course_certificate_courseenrollment_lesson_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
